export const yellow = {
  id: "vert1",
  topLeft: {
    self: "yellow",
    up: "red",
    right: "yellow",
    down: "yellow",
    left: "green",
    num: 1,
    id: "yellow_topLeft",
  },
  topMid: {
    self: "yellow",
    up: "red",
    right: "yellow",
    down: "yellow",
    left: "yellow",
    num: 2,
    id: "yellow_topMid",
  },
  topRight: {
    self: "yellow",
    up: "red",
    right: "blue",
    down: "yellow",
    left: "yellow",
    num: 3,
    id: "yellow_topRight",
  },

  middleLeft: {
    self: "yellow",
    up: "yellow",
    right: "blue",
    down: "yellow",
    left: "yellow",
    num: 4,
    id: "yellow_middleLeft",
  },
  middleMid: {
    self: "yellow",
    up: "yellow",
    right: "yellow",
    down: "yellow",
    left: "yellow",
    num: 5,
    id: "yellow_middleMid",
  },
  middleRight: {
    self: "yellow",
    up: "yellow",
    right: "blue",
    down: "yellow",
    left: "yellow",
    num: 6,
    id: "yellow_middleRight",
  },

  bottomLeft: {
    self: "yellow",
    up: "yellow",
    right: "blue",
    down: "orange",
    left: "green",
    num: 7,
    id: "yellow_bottomLeft",
  },
  bottomMid: {
    self: "yellow",
    up: "yellow",
    right: "yellow",
    down: "orange",
    left: "yellow",
    num: 8,
    id: "yellow_bottomMid",
  },
  bottomRight: {
    self: "yellow",
    up: "yellow",
    right: "blue",
    down: "orange",
    left: "yellow",
    num: 9,
    id: "yellow_bottomRight",
  },
};
export const white = {
  id: "vert2",
  topLeft: {
    self: "white",
    up: "orange",
    right: "white",
    down: "white",
    left: "green",
    num: 1,
    id: "white_topLeft",
  },
  topMid: {
    self: "white",
    up: "orange",
    right: "white",
    down: "white",
    left: "white",
    num: 2,
    id: "white_topMid",
  },
  topRight: {
    self: "white",
    up: "orange",
    right: "blue",
    down: "white",
    left: "white",
    num: 3,
    id: "white_topRight",
  },

  middleLeft: {
    self: "white",
    up: "white",
    right: "blue",
    down: "white",
    left: "green",
    num: 4,
    id: "white_middleLeft",
  },
  middleMid: {
    self: "white",
    up: "white",
    right: "white",
    down: "white",
    left: "white",
    num: 5,
    id: "white_middleMid",
  },
  middleRight: {
    self: "white",
    up: "white",
    right: "blue",
    down: "white",
    left: "white",
    num: 6,
    id: "white_middleRight",
  },

  bottomLeft: {
    self: "white",
    up: "white",
    right: "blue",
    down: "red",
    left: "green",
    num: 7,
    id: "white_bottomLeft",
  },
  bottomMid: {
    self: "white",
    up: "white",
    right: "white",
    down: "red",
    left: "white",
    num: 8,
    id: "white_bottomMid",
  },
  bottomRight: {
    self: "white",
    up: "white",
    right: "blue",
    down: "red",
    left: "white",
    num: 9,
    id: "white_bottomRight",
  },
};
export const green = {
  id: "hori1",
  topLeft: {
    self: "green",
    up: "yellow",
    right: "green",
    down: "green",
    left: "red",
    num: 1,
    id: "green_topLeft",
  },
  topMid: {
    self: "green",
    up: "yellow",
    right: "green",
    down: "green",
    left: "green",
    num: 2,
    id: "green_topMid",
  },
  topRight: {
    self: "green",
    up: "yellow",
    right: "orange",
    down: "green",
    left: "green",
    num: 3,
    id: "green_topRight",
  },

  middleLeft: {
    self: "green",
    up: "green",
    right: "orange",
    down: "green",
    left: "red",
    num: 4,
    id: "green_middleLeft",
  },
  middleMid: {
    self: "green",
    up: "green",
    right: "green",
    down: "green",
    left: "green",
    num: 5,
    id: "green_middleMid",
  },
  middleRight: {
    self: "green",
    up: "green",
    right: "orange",
    down: "green",
    left: "green",
    num: 6,
    id: "green_middleRight",
  },

  bottomLeft: {
    self: "green",
    up: "green",
    right: "orange",
    down: "white",
    left: "red",
    num: 7,
    id: "green_bottomLeft",
  },
  bottomMid: {
    self: "green",
    up: "green",
    right: "green",
    down: "white",
    left: "green",
    num: 8,
    id: "green_bottomMid",
  },
  bottomRight: {
    self: "green",
    up: "green",
    right: "orange",
    down: "white",
    left: "green",
    num: 9,
    id: "green_bottomRight",
  },
};
export const blue = {
  id: "hori2",
  topLeft: {
    self: "blue",
    up: "yellow",
    right: "blue",
    down: "blue",
    left: "orange",
    num: 1,
    id: "blue_topLeft",
  },
  topMid: {
    self: "blue",
    up: "yellow",
    right: "blue",
    down: "blue",
    left: "blue",
    num: 2,
    id: "blue_topMid",
  },
  topRight: {
    self: "blue",
    up: "yellow",
    right: "red",
    down: "blue",
    left: "blue",
    num: 3,
    id: "blue_topRight",
  },

  middleLeft: {
    self: "blue",
    up: "blue",
    right: "red",
    down: "blue",
    left: "orange",
    num: 4,
    id: "blue_middleLeft",
  },
  middleMid: {
    self: "blue",
    up: "blue",
    right: "blue",
    down: "blue",
    left: "blue",
    num: 5,
    id: "blue_middleMid",
  },
  middleRight: {
    self: "blue",
    up: "blue",
    right: "red",
    down: "blue",
    left: "blue",
    num: 6,
    id: "blue_middleRight",
  },

  bottomLeft: {
    self: "blue",
    up: "blue",
    right: "red",
    down: "white",
    left: "orange",
    num: 7,
    id: "blue_bottomLeft",
  },
  bottomMid: {
    self: "blue",
    up: "blue",
    right: "blue",
    down: "white",
    left: "blue",
    num: 8,
    id: "blue_bottomMid",
  },
  bottomRight: {
    self: "blue",
    up: "blue",
    right: "red",
    down: "white",
    left: "blue",
    num: 9,
    id: "blue_bottomRight",
  },
};
export const orange = {
  id: "lati1",
  topLeft: {
    self: "orange",
    up: "yellow",
    right: "orange",
    down: "orange",
    left: "green",
    num: 1,
    id: "orange_topLeft",
  },
  topMid: {
    self: "orange",
    up: "yellow",
    right: "orange",
    down: "orange",
    left: "orange",
    num: 2,
    id: "orange_topMid",
  },
  topRight: {
    self: "orange",
    up: "yellow",
    right: "blue",
    down: "orange",
    left: "orange",
    num: 3,
    id: "orange_topRight",
  },

  middleLeft: {
    self: "orange",
    up: "orange",
    right: "blue",
    down: "orange",
    left: "green",
    num: 4,
    id: "orange_middleLeft",
  },
  middleMid: {
    self: "orange",
    up: "orange",
    right: "orange",
    down: "orange",
    left: "orange",
    num: 5,
    id: "orange_middleMid",
  },
  middleRight: {
    self: "orange",
    up: "orange",
    right: "blue",
    down: "orange",
    left: "orange",
    num: 6,
    id: "orange_middleRight",
  },

  bottomLeft: {
    self: "orange",
    up: "orange",
    right: "blue",
    down: "white",
    left: "green",
    num: 7,
    id: "orange_bottomLeft",
  },
  bottomMid: {
    self: "orange",
    up: "orange",
    right: "orange",
    down: "white",
    left: "orange",
    num: 8,
    id: "orange_bottomMid",
  },
  bottomRight: {
    self: "orange",
    up: "orange",
    right: "blue",
    down: "white",
    left: "orange",
    num: 9,
    id: "orange_bottomRight",
  },
};
export const red = {
  id: "lati2",
  topLeft: {
    self: "red",
    up: "yellow",
    right: "red",
    down: "red",
    left: "blue",
    num: 1,
    id: "red_topLeft",
  },
  topMid: {
    self: "red",
    up: "yellow",
    right: "red",
    down: "red",
    left: "red",
    num: 2,
    id: "red_topMid",
  },
  topRight: {
    self: "red",
    up: "yellow",
    right: "green",
    down: "red",
    left: "red",
    num: 3,
    id: "red_topRight",
  },

  middleLeft: {
    self: "red",
    up: "red",
    right: "green",
    down: "red",
    left: "blue",
    num: 4,
    id: "red_middleLeft",
  },
  middleMid: {
    self: "red",
    up: "red",
    right: "red",
    down: "red",
    left: "red",
    num: 5,
    id: "red_middleMid",
  },
  middleRight: {
    self: "red",
    up: "red",
    right: "green",
    down: "red",
    left: "red",
    num: 6,
    id: "red_middleRight",
  },

  bottomLeft: {
    self: "red",
    up: "red",
    right: "green",
    down: "white",
    left: "blue",
    num: 7,
    id: "red_bottomLeft",
  },
  bottomMid: {
    self: "red",
    up: "red",
    right: "red",
    down: "white",
    left: "red",
    num: 8,
    id: "red_bottomMid",
  },
  bottomRight: {
    self: "red",
    up: "red",
    right: "green",
    down: "white",
    left: "red",
    num: 9,
    id: "red_bottomRight",
  },
};
